sonar.projectKey=Thefirstalpha_SeedFlix
sonar.organization=thefirstalpha
sonar.projectName=SeedFlix
sonar.sourceEncoding=UTF-8
sonar.sources=src,server
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=dist/**,node_modules/**,data/**,server/data/**,public/**,docker/**,guidelines/**,.github/**,coverage/**,**/*.d.ts,src/app/i18n/locales/**,**/src/app/i18n/locales/**,**/src/app/i18n/locales/**/*,**/locales/en.ts,**/locales/fr.ts,server/i18n.ts,tests/**
sonar.coverage.exclusions=src/main.tsx,src/vite-env.d.ts,server/index.ts,tests/**,src/app/i18n/locales/**,**/src/app/i18n/locales/**,**/src/app/i18n/locales/**/*,**/locales/en.ts,**/locales/fr.ts,server/i18n.ts,src/**,tests/**
sonar.cpd.exclusions=src/app/i18n/locales/**,**/src/app/i18n/locales/**,**/src/app/i18n/locales/**/*,**/locales/en.ts,**/locales/fr.ts,server/i18n.ts,tests/**